### ISSUE TITLE
Load MySQL time zone definitions by default

### ISSUE THREAD

**Issue by timgraham** [jphalip/djangocore-box#14]
There's a test failure if the definitions aren't installed:

```
$ runtests2.7-mysql datetimes
E.
======================================================================
ERROR: test_21432 (datetimes.tests.DateTimesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/django/django/test/utils.py", line 217, in inner
    return test_func(*args, **kwargs)
  File "/django/tests/datetimes/tests.py", line 99, in test_21432
    self.assertEqual(qs[0], now)
  File "/django/django/db/models/query.py", line 176, in __getitem__
    return list(qs)[0]
  File "/django/django/db/models/query.py", line 140, in __iter__
    self._fetch_all()
  File "/django/django/db/models/query.py", line 962, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/django/django/db/models/sql/compiler.py", line 1092, in results_iter
    raise ValueError("Database returned an invalid value "
ValueError: Database returned an invalid value in QuerySet.datetimes(). Are time zone definitions for your database and pytz installed?

----------------------------------------------------------------------
```
The definitions can be installed like so:
```
$ mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -psecret mysql
```

References:
https://code.djangoproject.com/ticket/21629
http://dev.mysql.com/doc/refman/5.5/en/mysql-tzinfo-to-sql.html

**Comment by timgraham** [comment]
Closing since this project is unmaintained.
